version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ufobeep-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/ufobeep}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
      - OPENSKY_CLIENT_ID=${OPENSKY_CLIENT_ID}
      - OPENSKY_CLIENT_SECRET=${OPENSKY_CLIENT_SECRET}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://minio:9000}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-minioadmin}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-minioadmin}
      - S3_BUCKET=${S3_BUCKET:-ufobeep-media}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-encryption-key-here}
      - ENVIRONMENT=development
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ./api:/app
    networks:
      - ufobeep-network
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: ufobeep-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ufobeep
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ufobeep-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ufobeep-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ufobeep-network
    restart: unless-stopped

  # MinIO Object Storage (S3 compatible)
  minio:
    image: minio/minio:latest
    container_name: ufobeep-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ufobeep-network
    restart: unless-stopped

  # Matrix Synapse (optional for local testing)
  # synapse:
  #   image: matrixdotorg/synapse:latest
  #   container_name: ufobeep-synapse
  #   ports:
  #     - "8008:8008"
  #   volumes:
  #     - synapse_data:/data
  #   environment:
  #     - SYNAPSE_SERVER_NAME=localhost
  #     - SYNAPSE_REPORT_STATS=no
  #   networks:
  #     - ufobeep-network
  #   restart: unless-stopped

networks:
  ufobeep-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data:
  synapse_data: