name: ufobeep
description: "UFOBeep - Real-time sighting alert system"

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# App version and build number
version: 1.0.0-beta.6+6

environment:
  sdk: ^3.8.1

# ----------------------
# DEPENDENCIES
# ----------------------
dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^14.6.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Networking
  dio: ^5.7.0
  http: ^1.2.2
  
  # Local Storage
  shared_preferences: ^2.3.3
  
  # Camera & Media
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  photo_manager: ^3.0.0
  path_provider: ^2.1.4
  exif: ^3.3.0
  image: ^4.1.7
  gal: ^2.3.0
  audioplayers: ^6.0.0  # <-- Audio playback for Phase 0 alert sounds
  video_player: ^2.9.2  # <-- Video playback for composition screen
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Geolocation & Sensors
  geolocator: ^13.0.2
  sensors_plus: ^4.0.2
  device_info_plus: ^9.1.1
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.1
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0
  
  # Firebase Services
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.4
  firebase_analytics: ^11.3.3
  package_info_plus: ^8.0.3
  
  # URL Launcher
  url_launcher: ^6.3.1
  
  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  
  # Alerts & vibration
  flutter_local_notifications: ^17.2.4
  vibration: ^2.0.1
  
  # Anonymous ID generation
  uuid: ^4.5.1

# ----------------------
# DEV DEPENDENCIES
# ----------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lint rules
  flutter_lints: ^5.0.0
  
  # Code generation tools
  riverpod_generator: ^2.6.2
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

# ----------------------
# LAUNCHER ICONS - MANUALLY MANAGED
# No more flutter_launcher_icons - it kept generating wrong icons
# ----------------------

# ----------------------
# FLUTTER SECTION (ONLY ONE)
# ----------------------
flutter:
  # Ensures Material Icons are included
  uses-material-design: true

  # Assets — keeping directory include so new MP3s auto-load without adding them individually
  assets:
    - .env
    - assets/sounds/
    - assets/icons/

  # Allow Flutter to generate localization code if needed
  generate: true
