name: API CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'
  pull_request:
    branches: [main]
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run tests
        run: |
          cd api
          pytest --cov=app

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          cd api
          docker build -t ufobeep-api:latest .
      - name: Deploy to VPS
        run: |
          echo "Deploy step placeholder"