name: Mobile CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'app/**'
      - '.github/workflows/mobile.yml'
  pull_request:
    branches: [main]
    paths:
      - 'app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Install dependencies
        run: |
          cd app
          flutter pub get
      - name: Run tests
        run: |
          cd app
          flutter test
      - name: Analyze code
        run: |
          cd app
          flutter analyze

  build-android:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Build APK
        run: |
          cd app
          flutter build apk --release

  build-ios:
    needs: test
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Build iOS
        run: |
          cd app
          flutter build ios --release --no-codesign